version: '3'

services:
  app1: 
    build: 
      context: .
      dockerfile: app1/Dockerfile
    ports:
      - "81:80"
    links: 
      - database
    depends_on:
      - database

    environment: 
      DB_HOST: database
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: laravel_user
      DB_PASSWORD: 123456

  app2: 
    build: 
      context: .
      dockerfile: app2/Dockerfile
    ports:
      - "82:80"
    links: 
      - database
    depends_on:
      - database

    environment: 
      DB_HOST: database
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: laravel_user
      DB_PASSWORD: 123456

  app3: 
    build: 
      context: .
      dockerfile: app3/Dockerfile
    ports:
      - "83:80"
    links: 
      - database
    depends_on:
      - database

    environment: 
      DB_HOST: database
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: laravel_user
      DB_PASSWORD: 123456


  database:
    image: 'mysql:5.7'
    ports:
      - 13306:3306

    # the mysql image uses these to create database and users
    environment: 
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: '123456'
    volumes:
      - /var/www/html/db:/var/lib/mysql
      - ./website.sql:/docker-entrypoint-initdb.d/website.sql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    links: 
      - database
    depends_on:
      - database

    environment: 
      DB_HOST: database
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: laravel_user
      DB_PASSWORD: 123456

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8090:80
    links: 
      - database
    depends_on:
      - database

    environment: 
      DB_HOST: database
      PMA_HOST: database
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: laravel_user
      DB_PASSWORD: 123456

